### ISSUE TITLE
Configure TravisCI

### ISSUE THREAD

**Issue by pdpinch** [mitodl/sga-lti#1]
Should be part of the cookie-cutter

**Comment by blarghmatey** [comment]
This repo has been enabled on Travis and Heroku is now configured to automatically deploy the develop branch to the staging app.

**Comment by blarghmatey** [comment]
The initial deploy attempt failed. This is the tail of the build log.

```
     $ python manage.py collectstatic --noinput
       76 static files copied to '/app/staticfiles'.
-----> Running post-compile hook
-----> Running django migrations
       Traceback (most recent call last):
         File "manage.py", line 14, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 83, in handle
           verbosity=self.verbosity,
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/__init__.py", line 119, in call_command
           return command.execute(*args, **defaults)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/commands/showmigrations.py", line 36, in handle
           return self.show_list(connection, options['app_labels'])
         File "/app/.heroku/python/lib/python3.4/site-packages/django/core/management/commands/showmigrations.py", line 44, in show_list
           loader = MigrationLoader(connection, ignore_no_migrations=True)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/db/migrations/loader.py", line 49, in __init__
           self.build_graph()
         File "/app/.heroku/python/lib/python3.4/site-packages/django/db/migrations/loader.py", line 176, in build_graph
           self.applied_migrations = recorder.applied_migrations()
         File "/app/.heroku/python/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
           self.ensure_schema()
         File "/app/.heroku/python/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
           if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
         File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/base/base.py", line 233, in cursor
           cursor = self.make_cursor(self._cursor())
         File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/base/base.py", line 204, in _cursor
           self.ensure_connection()
         File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
           self.connect()
         File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/base/base.py", line 171, in connect
           self.connection = self.get_new_connection(conn_params)
         File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 207, in get_new_connection
           conn = Database.connect(**conn_params)
       TypeError: 'sslmode' is an invalid keyword argument for this function
 !     Push rejected, failed to compile Python app
```

**Comment by zags** [comment]
It looks like it is trying to connect to SQLite, despite the database URL being for postgres.  I'm not sure why

**Comment by blarghmatey** [comment]
This was my fault, I didn't have the Postgres addon set up before I tried the initial deploy. It's fixed now and shouldn't pose an issue.
