### ISSUE TITLE
500 error on student submitting a file

### ISSUE THREAD

**Issue by pdpinch** [mitodl/sga-lti#39]
I'm getting a 500 error currently when I try to submit a file. Looking at the stack trace, it seems to be an issue with the data in one of the fields being too large:

<details>
 <summary>500 error on student submission</summary>
```
2016-07-03T19:08:52.678505+00:00 app[web.1]: Traceback (most recent call last):
2016-07-03T19:08:52.678509+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2016-07-03T19:08:52.678472+00:00 app[web.1]: [2016-07-03 19:08:52] ERROR 10 [django.request] base.py:284 - [7db1d235-39db-4469-891d-e874ad9ab7b5] - Internal Server Error: /view-submission-as-student/2/2
2016-07-03T19:08:52.678508+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
2016-07-03T19:08:52.678509+00:00 app[web.1]: psycopg2.DataError: value too long for type character varying(100)
2016-07-03T19:08:52.678511+00:00 app[web.1]: 
2016-07-03T19:08:52.678511+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2016-07-03T19:08:52.678512+00:00 app[web.1]: 
2016-07-03T19:08:52.678510+00:00 app[web.1]: 
2016-07-03T19:08:52.678513+00:00 app[web.1]: Traceback (most recent call last):
2016-07-03T19:08:52.678513+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
2016-07-03T19:08:52.678515+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
2016-07-03T19:08:52.678516+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2016-07-03T19:08:52.678517+00:00 app[web.1]:     return view_func(request, course_id, *args, **kwargs)
2016-07-03T19:08:52.678519+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/forms/models.py", line 451, in save
2016-07-03T19:08:52.678520+00:00 app[web.1]:     self.instance.save()
2016-07-03T19:08:52.678519+00:00 app[web.1]:     submission_form.save()
2016-07-03T19:08:52.678515+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2016-07-03T19:08:52.678521+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/base.py", line 700, in save
2016-07-03T19:08:52.678521+00:00 app[web.1]:     force_update=force_update, update_fields=update_fields)
2016-07-03T19:08:52.678523+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/base.py", line 793, in _save_table
2016-07-03T19:08:52.678522+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/base.py", line 728, in save_base
2016-07-03T19:08:52.678525+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/base.py", line 843, in _do_update
2016-07-03T19:08:52.678517+00:00 app[web.1]:   File "./sga/backend/authentication.py", line 28, in _wrapped_view
2016-07-03T19:08:52.678518+00:00 app[web.1]:   File "./sga/views.py", line 73, in view_submission_as_student
2016-07-03T19:08:52.678525+00:00 app[web.1]:     return filtered._update(values) > 0
2016-07-03T19:08:52.678526+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 645, in _update
2016-07-03T19:08:52.678528+00:00 app[web.1]:     cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
2016-07-03T19:08:52.678523+00:00 app[web.1]:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
2016-07-03T19:08:52.678528+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
2016-07-03T19:08:52.678527+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1149, in execute_sql
2016-07-03T19:08:52.678529+00:00 app[web.1]:     cursor.execute(sql, params)
2016-07-03T19:08:52.678530+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
2016-07-03T19:08:52.678526+00:00 app[web.1]:     return query.get_compiler(self.db).execute_sql(CURSOR)
2016-07-03T19:08:52.678524+00:00 app[web.1]:     forced_update)
2016-07-03T19:08:52.678533+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2016-07-03T19:08:52.678534+00:00 app[web.1]: django.db.utils.DataError: value too long for type character varying(100)
2016-07-03T19:08:52.678530+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2016-07-03T19:08:52.678532+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
2016-07-03T19:08:52.678531+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
2016-07-03T19:08:52.678533+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
2016-07-03T19:08:52.698029+00:00 app[web.1]: {address space usage: 306405376 bytes/292MB} {rss usage: 38809600 bytes/37MB} [pid: 10|app: 0|req: 1/15] 10.230.212.101 () {54 vars in 1181 bytes} [Sun Jul  3 19:08:51 2016] POST /view-submission-as-student/2/2 => generated 27 bytes in 1492 msecs (HTTP/1.1 500) 2 headers in 77 bytes (36 switches on core 0)
2016-07-03T19:08:52.678539+00:00 app[web.1]: 
2016-07-03T19:08:52.678531+00:00 app[web.1]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
2016-07-03T19:08:52.678532+00:00 app[web.1]:     raise value.with_traceback(tb)
```
</details>

**Comment by pdpinch** [comment]
This seems to be the crux of it:

```
  File "/app/.heroku/python/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
psycopg2.DataError: value too long for type character varying(100)
```

**Comment by zags** [comment]
Should be fixed by https://github.com/mitodl/sga-lti/commit/683cfc3060de886705e579a71076a42ffb62263f; please verify

**Comment by pdpinch** [comment]
Works for me now.
