### ISSUE TITLE
500 error on attempting to access grader view with a user named `pdpinch-grader`

### ISSUE THREAD

**Issue by pdpinch** [mitodl/sga-lti#43]
I'm getting a 500 error in the grader view after assigning my test student to the grader, `ValueError: Cannot query "pdpinch_student": Must be "User" instance.`

Stack trace:

```
2016-07-05T22:39:13.601595+00:00 app[web.1]: Traceback (most recent call last):
2016-07-05T22:39:13.601597+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2016-07-05T22:39:13.601599+00:00 app[web.1]:     return view_func(request, course_id, *args, **kwargs)
2016-07-05T22:39:13.601596+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
2016-07-05T22:39:13.601599+00:00 app[web.1]:   File "./sga/backend/authentication.py", line 28, in _wrapped_view
2016-07-05T22:39:13.601600+00:00 app[web.1]:   File "./sga/views.py", line 286, in view_assignment
2016-07-05T22:39:13.601601+00:00 app[web.1]:     submission, _ = Submission.objects.get_or_create(student=student_user, assignment=assignment)
2016-07-05T22:39:13.601601+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
2016-07-05T22:39:13.601602+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 465, in get_or_create
2016-07-05T22:39:13.601597+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
2016-07-05T22:39:13.601603+00:00 app[web.1]:     return self.get(**lookup), False
2016-07-05T22:39:13.601603+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 378, in get
2016-07-05T22:39:13.601602+00:00 app[web.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
2016-07-05T22:39:13.601606+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1243, in add_q
2016-07-05T22:39:13.601604+00:00 app[web.1]:     clone = self.filter(*args, **kwargs)
2016-07-05T22:39:13.601607+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1174, in build_filter
2016-07-05T22:39:13.601608+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1071, in check_related_objects
2016-07-05T22:39:13.601608+00:00 app[web.1]:     self.check_query_object_type(value, opts, field)
2016-07-05T22:39:13.601604+00:00 app[web.1]:     return self._filter_or_exclude(False, *args, **kwargs)
2016-07-05T22:39:13.601605+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 808, in _filter_or_exclude
2016-07-05T22:39:13.601607+00:00 app[web.1]:     allow_joins=allow_joins, split_subq=split_subq,
2016-07-05T22:39:13.601583+00:00 app[web.1]: [2016-07-05 22:39:13] ERROR 17 [django.request] base.py:284 - [5b6af6ad-3d46-418e-8dd6-16ee3dc137d7] - Internal Server Error: /view-assignment/2/2
2016-07-05T22:39:13.601605+00:00 app[web.1]:     clone.query.add_q(Q(*args, **kwargs))
2016-07-05T22:39:13.601606+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1269, in _add_q
2016-07-05T22:39:13.601606+00:00 app[web.1]:     clause, _ = self._add_q(q_object, self.used_aliases)
2016-07-05T22:39:13.601604+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 790, in filter
2016-07-05T22:39:13.601608+00:00 app[web.1]:     self.check_related_objects(field, value, opts)
2016-07-05T22:39:13.601609+00:00 app[web.1]:     (value, opts.object_name))
2016-07-05T22:39:13.601610+00:00 app[web.1]: ValueError: Cannot query "pdpinch_student": Must be "User" instance.
2016-07-05T22:39:13.601609+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1055, in check_query_object_type
2016-07-05T22:39:13.602963+00:00 app[web.1]: {address space usage: 304705536 bytes/290MB} {rss usage: 36839424 bytes/35MB} [pid: 17|app: 0|req: 10/40] 10.69.17.189 () {50 vars in 1108 bytes} [Tue Jul  5 22:39:13 2016] GET /view-assignment/2/2 => generated 27 bytes in 65 msecs (HTTP/1.1 500) 2 headers in 77 bytes (1 switches on core 0)
2016-07-05T22:39:13.417854+00:00 heroku[router]: at=info method=POST path="/" host=mitodl-sga-lti-staging.herokuapp.com request_id=19fb9253-c303-431c-bf3a-7584b89a4bca fwd="107.77.192.106" dyno=web.1 connect=0ms service=54ms status=302 bytes=361
2016-07-05T22:39:13.572415+00:00 heroku[router]: at=info method=GET path="/view-assignment/2/2" host=mitodl-sga-lti-staging.herokuapp.com request_id=bddd163d-9807-410a-9ce0-4d4cbf112660 fwd="107.77.192.106" dyno=web.1 connect=1ms service=65ms status=500 bytes=104
```

In case it's relevant, here's my user record in the admin view:

<img width="684" alt="screen shot 2016-07-05 at 6 39 02 pm" src="https://cloud.githubusercontent.com/assets/430126/16602193/242f2360-42e0-11e6-8843-f377c3798f92.png">

I can view the document fine from the admin view. 

I'll see if I can reproduce with a fresh student user.

**Comment by pdpinch** [comment]
Same error on a new user:

```
2016-07-05T22:53:14.175988+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 808, in _filter_or_exclude
2016-07-05T22:53:14.175990+00:00 app[web.1]:     allow_joins=allow_joins, split_subq=split_subq,
2016-07-05T22:53:14.175990+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1174, in build_filter
2016-07-05T22:53:14.175986+00:00 app[web.1]:     clone = self.filter(*args, **kwargs)
2016-07-05T22:53:14.175989+00:00 app[web.1]:     clause, _ = self._add_q(q_object, self.used_aliases)
2016-07-05T22:53:14.175988+00:00 app[web.1]:     clone.query.add_q(Q(*args, **kwargs))
2016-07-05T22:53:14.175989+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1243, in add_q
2016-07-05T22:53:14.175991+00:00 app[web.1]:     self.check_related_objects(field, value, opts)
2016-07-05T22:53:14.175991+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1071, in check_related_objects
2016-07-05T22:53:14.175992+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1055, in check_query_object_type
2016-07-05T22:53:14.175984+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 465, in get_or_create
2016-07-05T22:53:14.175985+00:00 app[web.1]:     return self.get(**lookup), False
2016-07-05T22:53:14.175986+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/query.py", line 378, in get
2016-07-05T22:53:14.175993+00:00 app[web.1]:     (value, opts.object_name))
2016-07-05T22:53:14.175996+00:00 app[web.1]: ValueError: Cannot query "pdpinch-student2": Must be "User" instance.
2016-07-05T22:53:14.177268+00:00 app[web.1]: {address space usage: 307576832 bytes/293MB} {rss usage: 40083456 bytes/38MB} [pid: 18|app: 0|req: 34/70] 10.140.192.224 () {50 vars in 1110 bytes} [Tue Jul  5 22:53:14 2016] GET /view-assignment/2/2 => generated 27 bytes in 68 msecs (HTTP/1.1 500) 2 headers in 77 bytes (1 switches on core 0)
2016-07-05T22:53:14.175991+00:00 app[web.1]:     self.check_query_object_type(value, opts, field)
2016-07-05T22:53:14.175989+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1269, in _add_q
```
